### ISSUE TITLE
Error on Forward or Back

### ISSUE THREAD

**Issue by arman86** [mikesteele/dual-captions#125]
I assume that the forward/back arrows in the upper-left corner would go to the next/previous subtitle. However, these buttons have never worked for me. I get errors consistently: 
![image](https://user-images.githubusercontent.com/30092819/73486746-94282d00-435a-11ea-9cb8-44d348d84218.png)

**Comment by mikesteele-drizly** [comment]
Can you send a screenshot of the forward/back arrows? I don't think they're part of this app.

**Comment by arman86** [comment]
This has been on my screen for a few months I believe:
![image](https://user-images.githubusercontent.com/30092819/73491234-000e9380-4363-11ea-9a5f-284fc39eb43d.png)

**Comment by mikesteele-drizly** [comment]
That's not a part of this extension. I'd check `chrome://extensions` and
see if you have other Netflix extensions installed.

**Comment by arman86** [comment]
That is hilarious. Yes indeed. It must be from videospeed. May be I can make the above into a feature request then: speed control and next/prev subtitle buttons. :-)

**Comment by mikesteele** [comment]
Speed control is available in the in-video-player settings modal (click the gear icon). Since the in-video-player settings modal is unpopular (reading the Google Web Store reviews), I'll likely move it into the browser_action in a later release. (I remember you preferring 0.8 speed, I'll add that to the next release)

As for the next/prev subtitle action, it was requested in #114 so I'm going close this issue in favor of that one.

**Comment by arman86** [comment]
Thanks. 0.8 and 0.9 are the most common settings for me other than 1.0.
