### ISSUE TITLE
On YouTube, the additional captions are attached to the wrong DOM node.

### ISSUE THREAD

**Issue by roseperrone** [mikesteele/dual-captions#38]
Problem:
The temporary caption window that says "Spanish (autogenerated). Click <> for settings" has the class "caption-window", so the additional captions are attached to that window, which disappears in a second, so the additional captions also disappear.

Suggested fix:
In youtube.js, could you attach the captions to the DOM node with id="caption-window-1" or the DOM node that has the class "ytp-caption-window-bottom"?

**Comment by mikesteele** [comment]
Hi! :-)

I’ve noticed this before, thanks for finding a fix. Feel free to make a
pull request if you want, you can add that case to the selector here:
https://github.com/mikesteele/dual-captions/blob/4caf76a15a72f2ee248b02d6ed4e190ba974875f/public/content-scripts/config/youtube.js#L22


I’m currently on vacation so I can review your PR, or make my own, after
6/03.

Le dim. 27 mai 2018 à 08:33, Rose Perrone <notifications@github.com> a
écrit :

**Comment by mikesteele** [comment]
Fixed by PR #39  (thanks again!)

**Comment by roseperrone** [comment]
I hadn't tested the fix, and now I see this error (screenshot attached)
"Two Captions not found on page." Is this error related?

**Comment by mikesteele** [comment]
I can’t see your screenshot, but that error means content scripts were not injected. I often see it when I install the extension and try to use it on a YouTube tab I opened before I installed. (As content scripts aren’t injected retroactively) That case is expected, which is why I put to try refreshing in the error message. Does it happen on refresh?

**Comment by roseperrone** [comment]
Thanks for the quick response! The error does happen on refresh. I even
tried re-installing the extension and restarting chrome.

**Comment by mikesteele** [comment]
Oh and does it work on Netflix?

**Comment by roseperrone** [comment]
Thanks! I do see errors in the popup's console. Here's the whole log:

i18next::backendConnector: loaded namespace translations for language en
Object
logger.js:23 i18next: initialized Object
middleware.js:27 Middleware: ---
middleware.js:28 Middleware: STORE:  Object
middleware.js:29 Middleware: ACTION:  Object
middleware.js:30 Middleware: ---
logger.js:23 i18next: languageChanged en
actions.js:162 actions: Dispatching updateStoreFromDC()
middleware.js:27 Middleware: ---
middleware.js:28 Middleware: STORE:  Object
middleware.js:29 Middleware: ACTION:  Object
middleware.js:30 Middleware: ---
actions.js:97 turnDCOn: response:  undefined
middleware.js:27 Middleware: ---
middleware.js:28 Middleware: STORE:  Object
middleware.js:29 Middleware: ACTION:  Object
middleware.js:30 Middleware: ---
actions.js:128 actions: Can't get active tab ID, am I running locally?

I see no logs in the main page's console.
I don't have a Netflix subscription, sorry!

**Comment by mikesteele** [comment]
Thanks for sending these logs. I can see that the popup can't get the ID of
the current Chrome tab, which it needs to send a message to turn on
dual-captions. It's an odd error, and I'm not sure why it's happening, but
I'm fairly sure it's not due to your changes. (It might be the build I
uploaded to the Chrome store) I'll update you when I know more.

**Comment by mikesteele** [comment]
Hey Rose, I shipped a new version of the app to the Chrome Web Store. (v1.3.1) Curious if it fixes this issue for you. Let me know! :-)

**Comment by roseperrone** [comment]
Sorry, nope. I'm running v1.3.1, and I restarted Chrome and refreshed the
page, but I still see these logs in the extension's console:

i18next::backendConnector: loaded namespace translations for language en
Object
logger.js:23 i18next: initialized Object
middleware.js:27 Middleware: ---
middleware.js:28 Middleware: STORE:  Object
middleware.js:29 Middleware: ACTION:  Object
middleware.js:30 Middleware: ---
logger.js:23 i18next: languageChanged en
actions.js:162 actions: Dispatching updateStoreFromDC()
middleware.js:27 Middleware: ---
middleware.js:28 Middleware: STORE:  Object
middleware.js:29 Middleware: ACTION:  Object
middleware.js:30 Middleware: ---
actions.js:97 turnDCOn: response:  undefined
middleware.js:27 Middleware: ---
middleware.js:28 Middleware: STORE:  Object
middleware.js:29 Middleware: ACTION:  Object
middleware.js:30 Middleware: ---
actions.js:128 actions: Can't get active tab ID, am I running locally?

**Comment by mikesteele** [comment]
Thanks! I still have no idea. 😅

Whenever you have time, see if you get any errors trying to query the active tab ID yourself. You'll have to run these snippets from the popup's console. (I really appreciate you helping me debug this!)

(Adapted from https://github.com/mikesteele/dual-captions/blob/master/src/utils/chrome.js)

```
window.chrome.tabs.query({
  currentWindow: true,
  active: true
}, tabs => {
  console.log(`Current Window, Active Tab ID: ${tabs[0].id}`);
});
```

And

```
window.chrome.tabs.query({
  active: true
}, tabs => {
  console.log(`No current window, Active Tab ID: ${tabs[0].id}`);
});
```

When I run them, I get:
```
Current Window, Active Tab ID: 138
No current window, Active Tab ID: 138
```

**Comment by roseperrone** [comment]
Sorry for the delay! My output looks just like yours (the IDs are the same
in both the first and second log). I'll try to find out why the content
script isn't loading when I get some time this week.

**Comment by mikesteele** [comment]
Awesome! :-) Some relevant files to check:

In the manifest, content scripts are listed & injected based on what sites
match this regex:
https://github.com/mikesteele/dual-captions/blob/master/public/manifest.json#L27

The error you're specifically seeing is that DC didn't send a response. You
can see here (
https://github.com/mikesteele/dual-captions/blob/master/public/content-scripts/dual-captions.js#L11)
for all the message types DC can respond to, it always sends a response
object via `sendResponse()` back to the popup. Your logs show `turnDCOn:
response: undefined` which means that DC didn't respond to the turn on
message (start-observer), likely because DC wasn't injected.

Feel free to send any questions you have while debugging. You can always
email me at mike@steel.fm too.
