### ISSUE TITLE
If second subtitle language is in video, use it instead of Google Translate

### ISSUE THREAD

**Issue by zoumhane** [mikesteele/dual-captions#51]
i have just an idea in youtube if the subtitle is already exist (like TEDx videos) so no need to use google translate, and it will be better to use the existent subtitle

**Comment by mikesteele** [comment]
I agree. If the video has subtitles in multiple languages, you should be able to use it. The code base isn't written now to allow that, but I'm open to trying it in the future.

**Comment by mikesteele** [comment]
Just an update on this - I have a working version on the `intercept-captions` branch for YouTube only. I'll release this in August. :-)

**Comment by mikesteele** [comment]
PR opened - #52

**Comment by wendingp** [comment]
I just watched a TED video and want to post the same thing!

**Comment by mikesteele** [comment]
This should be released very soon - putting the final touches on PR #52 :-)

**Comment by mikesteele** [comment]
Ok, this has been released. :-) 

You can either uninstall & reinstall to get the update - or wait until your extension auto-updates. If you do wait for an auto-update, you'll need to re-accept permissions, because I added `webRequest` to replay YouTube caption requests. You can do this in `chrome://extensions`.

Captions that are from the video now have a checkmark. ✓
If no checkmark, it came from Google Translate.

This new feature seems to work great for TED Talks, because the translators use one translation file and keep the same times, but for videos with community-created captions, I notice that it doesn't work great now. I'll see if I can find a solution for that, but if you come across a video where it isn't working great, feel like to turn it off via `Use captions from video` in the Settings panel.

I've opened #54 for Amazon & Netflix in-video caption support.

If you have any feedback or come across issues, let me know!

Thank you guys for being engaged with the project. :-)
