### ISSUE TITLE
Strange behavior while watching "The Protector" on Netflix

### ISSUE THREAD

**Issue by garfieldnate** [mikesteele/dual-captions#72]
I'm watching ["The Protector"](https://www.netflix.com/watch/80189590) on Netflix. These are the subtitle choices:

![image](https://user-images.githubusercontent.com/778453/50059004-5e89aa00-0181-11e9-8fbe-238aeb2c821e.png)

I select "English" in the Netflix menu once to load it, then select "Turkish [CC]" in the Netrlix menu, and then I turn on dual captioning with the plugin, selecting "English" in the plugin menu.

Sometimes no subtitles are displayed. Sometimes only Turkish is displayed. I can't get them both to display. When I check the console, I see lots of 503 responses from google translate (google-translate-api.js:85):

![image](https://user-images.githubusercontent.com/778453/50059026-e1126980-0181-11e9-9c00-158e3f7c38d8.png)

The full response is here: [f.txt](https://github.com/mikesteele/dual-captions/files/2683981/f.txt)

I don't know why it's trying to hit Google translate when the subtitles are available from Netflix already.

* Plugin display should list the languages that have been loaded by the user already (the checkmark instructions were unclear to me; I wasn't sure where I was supposed to see a checkmark).
* Should not hit Google translate API if the selected second language is already available
* Should gracefully handle 503 responses from Google

**Comment by mikesteele** [comment]
Hi! First and foremost, sorry about the Google Translate 503. You can see from previous releases (v.1.5.0.1 and v1.4.3.1) that patching Google Translate has become a pain point of the project. I'm hoping to remove Google Translate reliance entirely in 2019. (I don't believe many users use/like Google Translate-d second captions)

As for why Netflix official captions use Google Translate, it's because I haven't cracked how Netflix encored their caption request URLs. You can see some sample requests here in the background page tests: https://github.com/mikesteele/dual-captions/blob/master/src/tests/background.test.js#L48 When I get the response, it doesn't have any language-related metadata in it, so I have to use Google Translate to guess the language. (See https://github.com/mikesteele/dual-captions/blob/master/public/content-scripts/netflix/processor.js#L61)

In the "no-more-Google-Translate" version of this project, I think asking the user "what language is this?" is the easiest approach. If you want to patch this, you could replace `processor.__guessLanguageOfCaptions` with other code (perhaps prompting the user) in the meantime.

By the way, here's a related project: https://github.com/dannvix/NflxMultiSubs They only target Netflix and might be a good match for you in the meantime.

**Comment by garfieldnate** [comment]
Interesting! Thanks for the response. Since you are planning on getting rid of the google translate stuff, you can just close this issue if you like.
There are probably some language detection packages that you could use out there. Quick google search gives me [franc](https://github.com/wooorm/franc). The amount of data that these systems would require you to bundle might be an issue, but if it's a really key feature then it might be worth it.

**Comment by mikesteele** [comment]
This is fixed in v1.6.0, with Google Translate support completely removed.

**Comment by mikesteele** [comment]
I may add that `franc` library in the future btw, appreciate the link. Personally, bundle size isn't a big deal to me, as the app is installed on machines and not served.

**Comment by garfieldnate** [comment]
Thanks a bunch! I'm excited to retry this.

**Comment by mikesteele** [comment]
Please let me know if the UX is confusing. (I know it'll be) Just hope it's useable.

**Comment by garfieldnate** [comment]
Ah yeah, it works for now but it's not the best. It would probably be best to save recently selected languages at the top of the huge language list and set the default to whatever the last selection was. Mine always starts out with English selected and it's a bit of a hunt to find German.
