### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Kaytomann** [mikesteele/dual-captions#77]
the program has not worked so when i made it on the original subtitle hidden and nothing working

**Comment by mikesteele** [comment]
See the last comment on issue #74 for a build you can choose. I'm working on v1.6.0 to fix this. Please be patient. :-)

**Comment by mikesteele** [comment]
This has been fixed in v1.6.0, which I uploaded to the Chrome Web Store last night. Your installed version should have auto-updated to the new version. (You can verify in chrome://extensions) 

If not, you can re-install it from the Chrome Web Store here: https://chrome.google.com/webstore/detail/two-captions-for-youtube/lpeonmjfimoijceaalocpgjjchocbiap

Thanks for being patient & let me know what you think of this new version. :)
