### ISSUE TITLE
youtube (cc)

### ISSUE THREAD

**Issue by fritzily** [mikesteele/dual-captions#78]
![Unbenannt](https://user-images.githubusercontent.com/49480827/55873859-0859d000-5b91-11e9-9da0-f12bfa9688ad.png)
hi

i tried it for hours but i didnt get it run. - any viedo can't show the 2 subtitels or one subtitel (when the plug in ) is aktiv. does i make something wrong? in my youtube i dont have the "cc" icon (see the picture what i have instead) maybe thats the problem?

thx josef

**Comment by mikesteele** [comment]
See issue #77 and issue #74. I'm working on the solution, please be patient. :-)

**Comment by mikesteele** [comment]
This has been fixed in v1.6.0, which I uploaded to the Chrome Web Store last night. Your installed version should have auto-updated to the new version. (You can verify in chrome://extensions)

If not, you can re-install it from the Chrome Web Store here: https://chrome.google.com/webstore/detail/two-captions-for-youtube/lpeonmjfimoijceaalocpgjjchocbiap

Thanks for being patient & let me know what you think of this new version. :)
