### ISSUE TITLE
new idea for the "dual capture"

### ISSUE THREAD

**Issue by fritzily** [mikesteele/dual-captions#79]
Yesterday I tried to get it to work - pretty long needed ... and the result was not what I hoped ...
I researched on the internet how to learn a language in this way. The result was that the most helpful thing is to have a word for word (!) Translation (de-coding). So it's easy to understand words. At first, it is unusual, because in the word for word translation grammatically wrong sentences arise. The interesting thing, however, is that the brain abstracts and learns the grammar of the other language.

short explanation in german (unfortunately german, but with subtitles you should understand it - she seems stupid, but this woman is a big women in the german speaking area - but unfortunately already deceased)
https://www.youtube.com/watch?v=b_D7k8dFjZg

Example dual-translation (this function or type of translation would be damn cool to integrate into the "plug-in")
https://www.youtube.com/watch?v=STb-JXIANEU

Please do not misunderstand this message. I do not want to talk or criticize anything bad here or play the teacher. i just want to bring in my idea of ​​which i am convinced - and maybe you can program this with a not too big mission - i (and maybe others here?) would also be willing to pay for this function. (and please also make it compatible with amazon, not just netflix :))

thx
Joseph

**Comment by mikesteele** [comment]
Hi Joseph!

Thanks for writing in. 

Firstly, I think one of the reasons why dual subtitles isn't a common feature on video sites is because the UX of it (user experience) isn't well understood. Some users left have reviews asking for the subtitles on the top and bottom of the screen, some want them in different colors, some want the second subtitles to be smaller than the first.

This is a new idea

**Comment by mikesteele** [comment]
Hi Joseph!

Thanks for writing in. I'm never offended and I really appreciate the ideas.

Firstly, I think one of the reasons why dual subtitles isn't a common feature on video sites is because the UX of it (user experience) isn't well understood. Some users left have reviews asking for the subtitles on the top and bottom of the screen, some want them in different colors, some want the second subtitles to be smaller than the first.

This is a new idea and as new apps that produce dual subtitles come out, I think we'll start to see what works for users.

As for the feasibility of the videos you sent - the challenge there is that YouTube and Netflix (and most other video sites) store captions as sentences, not individual words. I'd need to ship a tokenizer (similar perhaps to what @garfieldnate mentioned in #72) to break up the sentences. Even then, I'm not sure it'd really work.

**Comment by fritzily** [comment]
Thank you for your prompt reply!

I tried to understand everything - unfortunately I am not a proctor :)
at the idea of the 1 to 1 translation of every single word. what about working here with an automatic translation. then you have the original words of the spoken and thus individual words that you translate. so we have no whole sentences to work with, which have to be breake up. - sure, now and then it can lead to meaningful mistakes - but that is irrelevant when learning the language.

but if this is possible - i dont know! :)

greetings from austria
josef

**Comment by fritzily** [comment]
hi,

you still remember me? - is there any funktion planned like my old question was?
